### ISSUE TITLE
allow specification of more diverse kubectl verbs in functional testing

### ISSUE THREAD

**Issue by ilrudie** [tmobile/magtape#58]
**What would you like to be added**:
Investigate update to functional testing to allow verbs such as kubectl create instead of only supporting apply.

**Why is this needed**:
Adds capability to the CI to test a more diverse spectra of polices covering a wider variety of  changes which might be requested against a cluster.

**Comment by ilrudie** [comment]
Ideas:
```
  - manifests
  - test-deploy01.yaml
  - create:"kubectl create blah blah"
  - delete:test-deploy01.yaml
```

```
  - kind: deployments
    desired: fail
    script: 
    manifests:
      - test-deploy02.yaml
    singletons:
      - "kubectl create something"
```

```
  - kind: deployments
    desired: fail
    script: 
    manifests:
      - test-deploy02.yaml
    creates:
      - "something"
```
